# Generated by Django 4.2.7 on 2024-01-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_bg', models.CharField(max_length=10)),
                ('apellido_bg', models.CharField(max_length=150)),
                ('nombre_bg', models.CharField(max_length=150)),
                ('direccion_bg', models.TextField()),
                ('fecha_nacimiento_bg', models.DateField()),
                ('correo_bg', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bg', models.CharField(max_length=100)),
                ('cantidad_disponible_bg', models.IntegerField()),
                ('unidad_medida_bg', models.CharField(max_length=20)),
                ('fecha_caducidad_bg', models.DateField()),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bg', models.CharField(max_length=100)),
                ('precio_bg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad_bg', models.CharField(max_length=50)),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bg', models.CharField(max_length=100)),
                ('poblacion_bg', models.IntegerField()),
                ('capital_bg', models.CharField(max_length=50)),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bg', models.CharField(max_length=150)),
                ('descripcion_bg', models.TextField()),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_bg', models.IntegerField()),
                ('procedimiento_bg', models.TextField()),
                ('ingrediente_bg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.ingrediente')),
                ('platillo_bg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Facturacion.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='platillo',
            name='tipo_bg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Facturacion.tipo'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_bg', models.DateField()),
                ('estado_bg', models.CharField(max_length=50)),
                ('observaciones_bg', models.TextField()),
                ('cliente_bg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Facturacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlatillo',
            fields=[
                ('id_bg', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_bg', models.TextField()),
                ('calorias_bg', models.IntegerField()),
                ('fecha_bg', models.DateField()),
                ('platillo_bg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Facturacion.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.tipo'),
        ),
    ]
