# Generated by Django 4.2.7 on 2024-01-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_alter_receta_ingrediente_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_bg',
        ),
        migrations.AddField(
            model_name='detalleplatillo',
            name='pedido_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.pedido'),
        ),
        migrations.AlterField(
            model_name='detalleplatillo',
            name='platillo_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.platillo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.cliente'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='tipo_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.tipo'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingrediente_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Facturacion.ingrediente'),
        ),
    ]
