# Generated by Django 4.2.7 on 2024-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_remove_cliente_tipo_bg_detalleplatillo_pedido_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_disponible_bg',
            field=models.CharField(max_length=100),
        ),
    ]
